
!include <win32.mak>


all: srv_sguard.Dll


.c.obj:
	$(cc) /I..\..\include /I..\..\ $(cdebug) $(cflags) $(cvarsdll) -I. -DCI_BUILD_MODULE -DUNICODE $*.c

srv_sguard.Dll: srv_sguard.obj
	$(link) $(linkdebug) $(dlllflags) /LIBPATH:..\..\ c_icap.lib -def:srv_sguard.def -out:$*.Dll $** $(DLL_ENTRY)  $(EXTRA_LIBS)

clean:
	del *.obj *.dll *.lib

