/*This is autogenerated file*/

#ifndef __C_ICAP_CONF_H
#define __C_ICAP_CONF_H

/* Define USE_IPV6 if we are supporting ipv6 */
#if 0
#define USE_IPV6
#endif

#if 0
#define USE_SYSV_IPC
#endif

#if 0
#define USE_POSIX_FILE_LOCK
#endif

#if  0
#define USE_POSIX_MAPPED_FILES
#endif

#if 0
#define USE_POSIX_SEMAPHORES
#endif

#if 0
#define USE_PTHREADS_RWLOCK
#endif

#if 0
#define __CI_COMPAT
#endif

#define CI_SIZEOF_OFF_T 8

/* Define to `long int' if <sys/types.h> does not define. */
#if 0
#define off_t long int
#endif

/* Define to `unsigned int' if <sys/types.h> does not define. */
#if 0
#define size_t unsigned int
#endif

#if 0
#define uint16_t unsigned short
#endif

#if 0
#define uint32_t unsigned int
#endif

#if 0
#define uint8_t unsigned char
#endif

#endif
